In [1]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)
np.random.seed(42)


In [3]:
tokens = ["I", "love", "AI"]
seq_len = len(tokens)
d_model = 2

# Token embeddings
E = np.array([
    [1.0, 0.0],   # I
    [0.8, 0.6],   # love
    [0.0, 1.0]    # AI
])

print("Embeddings (E):")
print(E)


Embeddings (E):
[[1.  0. ]
 [0.8 0.6]
 [0.  1. ]]


In [5]:
# Learnable weight matrices

W_Q = np.random.randn(d_model, d_model)
W_K = np.random.randn(d_model, d_model)
W_V = np.random.randn(d_model, d_model)

print("\nW_Q:\n", W_Q)
print("\nW_K:\n", W_K)
print("\nW_V:\n", W_V)



W_Q:
 [[ 0.242 -1.913]
 [-1.725 -0.562]]

W_K:
 [[-1.013  0.314]
 [-0.908 -1.412]]

W_V:
 [[ 1.466 -0.226]
 [ 0.068 -1.425]]


In [9]:
Q = E @ W_Q
K = E @ W_K
V = E @ W_V

print("\nQueries (Q):")
print(Q)

print("\nKeys (K):")
print(K)

print("\nValues (V):")
print(V)



Queries (Q):
[[ 0.242 -1.913]
 [-0.841 -1.868]
 [-1.725 -0.562]]

Keys (K):
[[-1.013  0.314]
 [-1.355 -0.596]
 [-0.908 -1.412]]

Values (V):
[[ 1.466 -0.226]
 [ 1.213 -1.035]
 [ 0.068 -1.425]]


In [7]:
S = Q @ K.T
print("\nSimilarity Scores (QKᵀ):")
print(S)



Similarity Scores (QKᵀ):
[[-0.846  0.812  2.482]
 [ 0.265  2.253  3.402]
 [ 1.57   2.673  2.36 ]]


In [ ]:
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

scaled_S = S / np.sqrt(d_model)

A = softmax(scaled_S)

print("\nAttention Weights:")
print(A)



Attention Weights:
[[0.246 0.332 0.422]
 [0.123 0.284 0.593]
 [0.096 0.26  0.644]]


In [7]:
C = A @ V

print("\nContext Vectors:")
print(C)



Context Vectors:
[[-0.528 -0.012]
 [-0.518 -0.166]
 [-0.513 -0.208]]
