In [1]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)
np.random.seed(42)


In [2]:
tokens = ["I", "love", "AI"]

seq_len = len(tokens)
d_model = 2  # small for clarity

# Token embeddings
E = np.array([
    [1.0, 0.0],   # I
    [0.8, 0.6],   # love
    [0.0, 1.0]    # AI
])

print("Embeddings (E):")
print(E)


Embeddings (E):
[[1.  0. ]
 [0.8 0.6]
 [0.  1. ]]


In [3]:
W_Q = np.random.randn(d_model, d_model)
W_K = np.random.randn(d_model, d_model)
W_V = np.random.randn(d_model, d_model)

print("\nW_Q:\n", W_Q)
print("\nW_K:\n", W_K)
print("\nW_V:\n", W_V)



W_Q:
 [[ 0.497 -0.138]
 [ 0.648  1.523]]

W_K:
 [[-0.234 -0.234]
 [ 1.579  0.767]]

W_V:
 [[-0.469  0.543]
 [-0.463 -0.466]]


In [4]:
Q = E @ W_Q
K = E @ W_K
V = E @ W_V

print("\nQueries (Q):")
print(Q)

print("\nKeys (K):")
print(K)

print("\nValues (V):")
print(V)



Queries (Q):
[[ 0.497 -0.138]
 [ 0.786  0.803]
 [ 0.648  1.523]]

Keys (K):
[[-0.234 -0.234]
 [ 0.76   0.273]
 [ 1.579  0.767]]

Values (V):
[[-0.469  0.543]
 [-0.654  0.155]
 [-0.463 -0.466]]


In [5]:
d_k = Q.shape[-1]

scores = Q @ K.T
scaled_scores = scores / np.sqrt(d_k)

print("\nScaled Attention Scores:")
print(scaled_scores)



Scaled Attention Scores:
[[-0.059  0.24   0.48 ]
 [-0.263  0.578  1.314]
 [-0.359  0.642  1.55 ]]


In [6]:
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

attention_weights = softmax(scaled_scores)

print("\nAttention Weights:")
print(attention_weights)

print("\nRow sums (should be 1):")
print(attention_weights.sum(axis=1))



Attention Weights:
[[0.246 0.332 0.422]
 [0.123 0.284 0.593]
 [0.096 0.26  0.644]]

Row sums (should be 1):
[1. 1. 1.]


In [7]:
context_vectors = attention_weights @ V

print("\nContext Vectors:")
print(context_vectors)



Context Vectors:
[[-0.528 -0.012]
 [-0.518 -0.166]
 [-0.513 -0.208]]
