In [ ]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()
input_= pd.DataFrame(data=iris['data'], columns=iris.feature_names)
target_ = pd.DataFrame(data=iris['target'], columns=['type'])
data = pd.concat([input_, target_], axis=1)
data.head(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),type
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, DecisionTreeClassifier

X = data
y = data.pop('type')
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3)

adb = AdaBoostClassifier(
    base_estimator=DecisionTreeClassifier(
        max_depth=2,
        min_samples_leaf=5
    ),
    n_estimators=100,
    learning_rate=0.1,
    algorithm="SAMME.R",
    random_state=42
)

model = adb.fit(X_train, Y_train)
y_pred = model.predict(X_test)
y_pred

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))
print(accuracy_score(Y_test, y_pred))

[[12  0  0]
 [ 0 15  1]
 [ 0  4 13]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.79      0.94      0.86        16
          2       0.93      0.76      0.84        17

avg / total       0.90      0.89      0.89        45

0.8888888888888888


<hr></hr>