In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


In [2]:
# Load dataset
X, y = load_iris(return_X_y=True)

# Train–test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)


In [10]:
X[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
set(y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
len(y)

150

In [16]:
{i: list(y).count(i) for i in set(y)}

{np.int64(0): 50, np.int64(1): 50, np.int64(2): 50}

In [3]:
from sklearn.naive_bayes import GaussianNB

# Gaussian Naive Bayes assumes:
# x_j | y ~ Normal(mean_{jy}, var_{jy})
nb = GaussianNB()

# MLE happens here
nb.fit(X_train, y_train)


,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09


In [ ]:
# Class predictions (argmax_y P(y|x))
y_pred = nb.predict(X_test)

# Full posterior probabilities P(y|x)
y_proba = nb.predict_proba(X_test)


In [20]:
X_test

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3

In [22]:
input_ = np.array([[6.1, 2.8, 4.7, 1.2]])
nb.predict_proba(input_)

array([[4.15880005e-88, 9.95527834e-01, 4.47216606e-03]])

In [23]:
y_proba = nb.predict_proba(X_test)

In [27]:
y_proba

array([[4.15880005e-088, 9.95527834e-001, 4.47216606e-003],
       [1.00000000e+000, 1.31031235e-013, 2.21772205e-020],
       [9.83170191e-285, 2.70138564e-012, 1.00000000e+000],
       [9.54745274e-092, 9.74861431e-001, 2.51385686e-002],
       [1.08679560e-103, 8.31910700e-001, 1.68089300e-001],
       [1.00000000e+000, 6.77693844e-013, 7.14891338e-021],
       [2.79985841e-051, 9.99963925e-001, 3.60749274e-005],
       [3.47130487e-172, 4.26099520e-007, 9.99999574e-001],
       [8.87424368e-094, 9.93578115e-001, 6.42188515e-003],
       [1.01525828e-057, 9.99952885e-001, 4.71152410e-005],
       [3.89708229e-148, 2.58773323e-004, 9.99741227e-001],
       [1.00000000e+000, 1.41103765e-016, 9.36331484e-025],
       [1.00000000e+000, 2.50761563e-016, 5.99383407e-024],
       [1.00000000e+000, 3.02382725e-016, 3.69654979e-024],
       [1.00000000e+000, 2.31820777e-016, 1.18856457e-023],
       [6.09343428e-105, 4.23901472e-001, 5.76098528e-001],
       [8.42661111e-199, 2.69249362e-007

In [29]:
for i in y_proba:
    for idx, j in enumerate(i):
        if j == max(i):
            print(idx, j)
        else:
            continue

1 0.9955278339441787
0 0.999999999999869
2 0.999999999997299
1 0.9748614313921319
1 0.8319107003486937
0 0.9999999999993223
1 0.999963925072563
2 0.9999995739004797
1 0.9935781148470645
1 0.9999528847590333
2 0.9997412266770822
0 0.9999999999999999
0 0.9999999999999998
0 0.9999999999999997
0 0.9999999999999998
2 0.5760985275153628
2 0.9999997307506379
1 0.9999887588595633
1 0.9981929164133523
2 0.9999980898109634
0 0.9999999999999973
2 0.9295149754135278
0 0.9999999999995611
2 0.9999874681066233
2 0.9999999998332711
2 0.999999398338981
2 0.99944611227894
2 0.9999999950961023
0 0.9999999999999873
0 0.9999999999999937
0 1.0
0 1.0
1 0.9502266888101203
0 0.9999999999999992
0 0.9999999999999999
2 0.974419447498156
1 0.8704209165568798
0 0.9999999999999997
0 1.0
0 1.0
2 0.9767076756729156
1 0.7189237297779977
1 0.6190348287448522
0 0.9999999999999987
0 0.9999999999999998


In [5]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", round(accuracy_score(y_test, y_pred),2))
print(classification_report(y_test, y_pred))


Accuracy: 0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [6]:
# Inspect learned parameters
print("Class priors P(y):\n", nb.class_prior_)
print("\nMeans (mu_{jy}):\n", nb.theta_)
print("\nVariances (sigma^2_{jy}):\n", nb.var_)


Class priors P(y):
 [0.2952381  0.35238095 0.35238095]

Means (mu_{jy}):
 [[4.96451613 3.37741935 1.46451613 0.2483871 ]
 [5.86216216 2.72432432 4.21081081 1.3027027 ]
 [6.55945946 2.98648649 5.54594595 2.00540541]]

Variances (sigma^2_{jy}):
 [[0.1119667  0.13658689 0.03325703 0.01152966]
 [0.27532506 0.08724617 0.23934259 0.04134405]
 [0.42241052 0.09630387 0.28842951 0.08591673]]
